pipeline {
    agent any
    stages {

        stage('Clone Repo') {
          steps {
              withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin']){
            sh 'git clone https://github.com/Raghurapaka/pipeline.git'
              }
            }
        }

        stage('Build Docker Image') {
          steps {
             withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin']){  
            sh 'cd /var/lib/jenkins/workspace/pipeline3/pipeline'
            sh ' cp  /var/lib/jenkins/workspace/pipeline3/pipeline/* /var/lib/jenkins/workspace/pipeline2'
            sh ' docker rmi raghurapaka/pipelinetest:v1'
            sh 'docker build -t raghurapaka/pipelinetest:v1 .'
             }
            }
        }

        stage('Push Image to Docker Hub') {
          steps {
           withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin']){   
           sh    'docker push raghurapaka/pipelinetest:v1'
           }
           }
        }

        stage('Deploy to Docker Host') {
          steps {
             withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin']){  
            sh    'docker -H tcp://10.1.1.44:2375 stop webapp1'
            sh    'docker -H tcp://10.1.1.44:2375 run --rm -dit --name webapp1 --hostname webapp1 -p 9000:80 sreeharshav/pipelinetest:v1'
             }
            }
        }

        stage('Check WebApp Rechability') {
          steps {
           withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin']){    
          sh 'sleep 10s'
          sh 'curl http://ec2-34-224-23-15.compute-1.amazonaws.com:9000'
           }
          }
        }

    }
}
