pipeline {
    agent any
    stages {

        stage('Clone Repo') {
          steps {
            sh 'rm -rf dockertest1'
            sh 'git clone https://github.com/mavrick202/dockertest1.git'
            }
        }

        stage('Build Docker Image') {
          steps {
            sh 'cd /var/lib/jenkins/workspace/pipeline2/dockertest1'
            sh ' cp  /var/lib/jenkins/workspace/pipeline2/dockertest1/* /var/lib/jenkins/workspace/pipeline2'
            sh 'docker build -t raghurapaka/pipelinetest:v2 .'
            }
        }

        stage('Push Image to Docker Hub') {
          steps {
           sh    'docker push raghurapaka/pipelinetest:v2'
           }
        }

        stage('Deploy to Docker Host') {
          steps {
            sh   'docker -H tcp://10.1.1.44:2375 run --rm -dit --name webapp1 --hostname webapp1 -p 9000:80 raghurapaka/pipelinetest:v2'
            }
        }

        stage('Check WebApp Rechability') {
          steps {
          sh 'sleep 10s'
          sh 'curl http://ec2-34-224-23-15.compute-1.amazonaws.com:9000'
          }
        }

    }
}
